1. updated play midi note
LiXizhi/NPLRuntime pull request #520
Opened 2022-05-30 03:41 UTC by onedou

2. added stop midi note

2022-05-30 03:51 UTC, LiXizhi requested changes

2022-05-30 03:51 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/util/MidiMsg.cpp
> +int CMidiMsg::StopMidiMsg()
加入需要暂停的频道。

2022-06-01 10:20 UTC, closed without merging

2022-06-27 03:28 UTC, fengyinz commented
@LiXizhi 修bug https://github.com/LiXizhi/ParaCraft/issues/296

2022-06-27 03:29 UTC, fengyinz commented on Client/trunk/ParaEngineClient/util/MidiMsg.cpp
> +int CMidiMsg::StopMidiMsg()
修bug @Lixizhi 
https://github.com/LiXizhi/ParaCraft/issues/296