动态物理
LiXizhi/NPLRuntime pull request #550
Opened 2022-09-15 09:01 UTC by wxaxiaoyao

// 我们可以提供一些内置的常用形状,例如
// “sphere“   半径为biped的默认半径
// “aabb“ biped的默认AABB大小即可
// “capsule“ biped的默认AABB大小的胶囊。 圆柱体上下加半球体
CBipedObject:SetPhysicalShape(shape:string)

// 启动对象的动态物理仿真
// 然后直接在FrameMove中实现，数据从物理引擎世界到渲染世界的同步。 
CBipedObject::EnableDynamicPhysics(boolean)

2022-09-15 10:25 UTC, LiXizhi requested changes

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/ParaEngine/3dengine/BaseObject.cpp
> +std::string ParaEngine::CBaseObject::GetPhysicsShape()
return const char*  or   const std::string&

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/ParaEngine/3dengine/BaseObject.h
> +	virtual std::string GetPhysicsShape();
const char*

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/ParaEngine/ParaScriptBindings/ParaScriptingScene.cpp
> +void ParaScene::EnabledDynamicsSimulation(bool bEnable)
spelling  DynamicSimulation

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/ParaEngine/math/ParaQuaternion.cpp
> +    void Quaternion::ToEulerAnglesSequence(float& pitch, float& yaw, float& roll, std::string rotSeq) const
use     const std::string& rotSeq

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/ParaEngine/math/ParaQuaternion.h
> +		void threeaxisrot(float r11, float r12, float r21, float r31, float r32, float& out1, float out2, float& out3) const
move implementation to cpp?

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.cpp
> +	BulletSimpleShape* pShape = new BulletSimpleShape();
is this reference counted and properly released?

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.cpp
>  IParaPhysicsShape* CParaPhysicsWorld::CreateTriangleMeshShap(const ParaPhysicsTriangleMeshDesc& meshDesc)
CreateTriangleMeshShape   spelling error, last e

2022-09-15 10:25 UTC, LiXizhi commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.h
> -		void* m_pUserData;
better make IParaPhysiscsActor pure

2022-09-16 02:15 UTC, wxaxiaoyao commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.cpp
> +	BulletSimpleShape* pShape = new BulletSimpleShape();
![image](https://user-images.githubusercontent.com/11922085/190541657-9eb4b943-97c9-422a-bbd4-69fd50595e8f.png)
一个biped对象对应一个actor shape, shape  随actor删除而删除

2022-09-16 02:18 UTC, wxaxiaoyao commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.h
> -		void* m_pUserData;
目前只有biped对象做模拟, 后续如果其它对象也有需求, 不在基类实现会有大量重复代码, 目前接入的功能比价简单, 后续引入其它功能可能也会产生数据缓存

2022-09-16 04:02 UTC, LiXizhi requested changes
minor fix

2022-09-16 04:02 UTC, LiXizhi commented on NPLRuntime/ParaEngine/math/ParaQuaternion.cpp
> +        if(rotSeq == "yxz")
if rotSeq is char , you need to use strcmp

2022-09-16 04:02 UTC, LiXizhi commented on NPLRuntime/ParaEngine/math/ParaQuaternion.cpp
> +    void Quaternion::ToEulerAnglesSequence(float& pitch, float& yaw, float& roll, const char* rotSeq) const
needs to use const std::string&,  
otherwise there is no == operation

2022-09-16 04:02 UTC, LiXizhi commented on NPLRuntime/Plugins/PhysicsBT/ParaPhysicsWorld.cpp
> +	BulletSimpleShape* pShape = new BulletSimpleShape();
better release shape, when actor is released in actor destructor class

2022-09-16 08:13 UTC, merged