分裂方块功能。
LiXizhi/NPLRuntime pull request #81
Opened 2017-07-06 03:02 UTC by jinganglang0013

1.可分裂方块功能（分裂，选中框，切换颜色，切换贴图）
2.保存可分裂方块。
3.支持命令栈。
4.没保存BMAX文件。

2017-07-06 10:19 UTC, kkvskkkk commented on Client/trunk/ParaEngineClient/BlockEngine/BlockWorld.cpp
> +}
if (i >=0 && i <= 7)
 return i + '0';
else
 return '0';

2017-07-06 10:19 UTC, kkvskkkk commented on Client/trunk/ParaEngineClient/BlockEngine/RenderableChunk.h
> +
InstanceGroupIndex():m_index(0)

用构造列表会快一点， std::string 不用赋值就是""

2017-07-10 09:37 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/BlockChunk.h
> +        void* m_blockExtData;   ///< 复杂方块用2017.4.18
union

2017-07-10 09:39 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/BlockRegion.h
> +		int level;
limit size to int16

2017-07-10 09:41 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/BlockRenderTask.cpp
> +		m_textureIndex = textureidx;
rename

2017-07-10 09:45 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/RenderableChunk.cpp
> +			std::vector<string> levelVec = pInstGroup->levels;
refrence

2017-07-10 09:46 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/RenderableChunk.cpp
> +		BlockTemplate *pTemplate = pWord->GetBlockTemplate(m_templateId);
spelling pWord->pWorld

2017-07-10 09:50 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/SplitModelProvider.cpp
> +		assert(src);
@kkvskkkk  unify assertions

2017-07-10 09:51 UTC, LiXizhi commented on Client/trunk/ParaEngineClient/BlockEngine/SplitModelProvider.cpp
> +			if (num == 8)
use MACRO

2017-08-04 16:00 UTC, LiXizhi requested changes
@jinganglang0013   please fix and support coplanar bmax face merge as in BMAXParser.  and fix various conflicts.

2022-11-16 11:11 UTC, closed without merging